releasenotes/urls.py
from django.urls import path

from releasenotes import views

app_name = "releasenotes"

urlpatterns = [
    path("<slug:project_slug>/", views.ReleaseNotesProjectView.as_view(), name="project-details"),
    path("<slug:project_slug>/<str:release_slug>/", views.ReleaseNotesDetailView.as_view(), name="release-details"),
]

releasenotes/templates/releasenotes/base.html
{% extends "base.html" %}

{% block content %}

  {% block release_content %}
  {% endblock %}

{% endblock %}

releasenotes/templates/releasenotes/index.html
{% extends "releasenotes/base.html" %}

{% block title %}Release Notes - Home{% endblock %}

{% block content %}
<h1>Release Notes Base HTML Template</h1>
{% comment %} <a href="{% url 'releasenotes:project-details' %}">Release Notes</a> {% endcomment %}
{% for project in object_list %}
<a href="{{project.get_absolute_url}}">{{project.name}}</a>
{% empty %}
{% endfor %}
{% endblock %}

releasenotes/templates/releasenotes/project_detail.html
{% extends "releasenotes/base.html" %}
{% load markdownify %}
{% load i18n %}

{% block title %}Release Notes - Home{% endblock %}

{% block release_content %}
<h1>{{ object.project.name }}</h1>

<h3>Releases</h3>

{% comment %} TODO: This should display the details of the most current release and then a list of all the other release below.  Probably should be handled in the view context. {% endcomment %}

<ul>
{% for release in object.releases.all %}
<li><a href="{{ release.get_absolute_url }}">{{ release.version_name }}</a> - Date</li>
{% endfor %}
</ul>

{% endblock %}

releasenotes/templates/releasenotes/release_detail.html
{% extends "releasenotes/base.html" %}
{% load markdownify %}
{% load i18n %}

{% block title %}{{ object.project.name }} {{object.version_name}} - Release Notes{% endblock %}

{% block release_content %}
<h1>{{ object.project.name }}</h1>

<h3>Release: <a href="{{object.get_absolute_url}}">{{object.version_name}}</a></h3>

{% if new_features %}
<h4>New Features</h4>
{% for new_feature in new_features %}
{% if new_feature.audience %}<p><h6>{{ new_feature.audience.name }}</h6>{% endif %}
{{ new_feature.description|markdownify }}
{% endfor %}
<p>
{% endif %}

{% if bug_fixes %}
<h4>Bug Fixes</h4>
{% for bug_fix in bug_fixes %}
{% if bug_fix.audience %}<p><h6>{{ bug_fix.audience.name }}</h6>{% endif %}
{{ bug_fix.description|markdownify }}
{% endfor %}
<p>
{% endif %}

{% if known_issues %}
<h4>Known Issues</h4>
{% for known_issue in known_issues %}
{% if known_issue.audience %}<p><h6>{{ known_issue.audience.name }}</h6>{% endif %}
{{ known_issue.description|markdownify }}
{% endfor %}
<p>
{% endif %}

{% endblock %}